
on:
    pull_request:
      branches:
        - main
jobs:
    quick-scan:
      runs-on: ubuntu-latest
      env:
        AUDIT_AGENT_TOKEN: ${{ secrets.AUDIT_AGENT_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - name: Quick Scan
          run: |
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-Api-Key: $AUDIT_AGENT_TOKEN" \
              -d '{
                "repository_url": "${{ github.event.repository.html_url }}",
                "branch_name": "${{ github.event.pull_request.head.ref }}",
                "issue_number": "${{ github.event.number }}",
                "commit_hash": "${{ github.event.pull_request.head.sha}}",
                "files": ["src/AgentToken.sol","src/Counter.sol"]
              }' \
              https://e2f6-2405-201-2017-c802-c5d0-b485-fa1d-33a3.ngrok-free.app/v1/quick-scan/launch
